displayName=True Tile Movement Animations
author=Posiedien
description=Replaces the game's standard character movement animations with a custom movement model that closely follows the true tile.
tags=true tile, movement, animation, pathing, pvm, tick, inferno, raids
version=1.0.3
plugins=com.truetileanimationmovement.TrueTileMovementPlugin
build=standard